config/routes.rb
# == Route Map
#
#             Prefix Verb   URI Pattern                                      Controller#Action
#               root GET    /                                                welcome#index
#      post_comments POST   /posts/:post_id/comments(.:format)               comments#create
#       post_comment DELETE /posts/:post_id/comments/:id(.:format)           comments#destroy
#              posts GET    /posts(.:format)                                 posts#index
#                    POST   /posts(.:format)                                 posts#create
#           new_post GET    /posts/new(.:format)                             posts#new
#          edit_post GET    /posts/:id/edit(.:format)                        posts#edit
#               post GET    /posts/:id(.:format)                             posts#show
#                    PATCH  /posts/:id(.:format)                             posts#update
#                    PUT    /posts/:id(.:format)                             posts#update
#                    DELETE /posts/:id(.:format)                             posts#destroy
#                    GET    /posts(.:format)                                 posts#index
#                    POST   /posts(.:format)                                 posts#create
#                    GET    /posts/new(.:format)                             posts#new
#                    GET    /posts/:id/edit(.:format)                        posts#edit
#                    GET    /posts/:id(.:format)                             posts#show
#                    PATCH  /posts/:id(.:format)                             posts#update
#                    PUT    /posts/:id(.:format)                             posts#update
#                    DELETE /posts/:id(.:format)                             posts#destroy
#     bulletin_posts GET    /bulletins/:bulletin_id/posts(.:format)          posts#index
#                    POST   /bulletins/:bulletin_id/posts(.:format)          posts#create
#  new_bulletin_post GET    /bulletins/:bulletin_id/posts/new(.:format)      posts#new
# edit_bulletin_post GET    /bulletins/:bulletin_id/posts/:id/edit(.:format) posts#edit
#      bulletin_post GET    /bulletins/:bulletin_id/posts/:id(.:format)      posts#show
#                    PATCH  /bulletins/:bulletin_id/posts/:id(.:format)      posts#update
#                    PUT    /bulletins/:bulletin_id/posts/:id(.:format)      posts#update
#                    DELETE /bulletins/:bulletin_id/posts/:id(.:format)      posts#destroy
#          bulletins GET    /bulletins(.:format)                             bulletins#index
#                    POST   /bulletins(.:format)                             bulletins#create
#       new_bulletin GET    /bulletins/new(.:format)                         bulletins#new
#      edit_bulletin GET    /bulletins/:id/edit(.:format)                    bulletins#edit
#           bulletin GET    /bulletins/:id(.:format)                         bulletins#show
#                    PATCH  /bulletins/:id(.:format)                         bulletins#update
#                    PUT    /bulletins/:id(.:format)                         bulletins#update
#                    DELETE /bulletins/:id(.:format)                         bulletins#destroy
# 

Rails.application.routes.draw do

  root 'welcome#index'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :posts
  resources :bulletins do
    resources :posts
  end
end

app/models/bulletin.rb
# == Schema Information
#
# Table name: bulletins
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  post_type    :string
#  post_type_cd :integer          default(0)
#

class Bulletin < ApplicationRecord
  has_many :posts, dependent: :destroy
  as_enum :post_type, bulletin: 0, blog: 1, gallery: 2
end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
  before_action :set_bulletin, only: [:show, :edit, :update, :destroy]

  # GET /bulletins
  # GET /bulletins.json
  def index
    @bulletins = Bulletin.all
  end

  # GET /bulletins/1
  # GET /bulletins/1.json
  def show
  end

  # GET /bulletins/new
  def new
    @bulletin = Bulletin.new
  end

  # GET /bulletins/1/edit
  def edit
  end

  # POST /bulletins
  # POST /bulletins.json
  def create
    @bulletin = Bulletin.new(bulletin_params)

    respond_to do |format|
      if @bulletin.save
        format.html { redirect_to @bulletin, notice: 'Bulletin was successfully created.' }
        format.json { render :show, status: :created, location: @bulletin }
      else
        format.html { render :new }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bulletins/1
  # PATCH/PUT /bulletins/1.json
  def update
    respond_to do |format|
      if @bulletin.update(bulletin_params)
        format.html { redirect_to @bulletin, notice: 'Bulletin was successfully updated.' }
        format.json { render :show, status: :ok, location: @bulletin }
      else
        format.html { render :edit }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bulletins/1
  # DELETE /bulletins/1.json
  def destroy
    @bulletin.destroy
    respond_to do |format|
      format.html { redirect_to bulletins_url, notice: 'Bulletin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bulletin
      @bulletin = Bulletin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bulletin_params
      params.require(:bulletin).permit(:title, :description, :post_type_cd)
    end
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/views/bulletins/_form.html.erb
<%= simple_form_for(@bulletin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description, input_html: { row: 5 } %>
    <%= f.input :post_type_cd, collection: enum_option_pairs(Bulletin, :post_type, true) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to 'Show', @bulletin, class: 'btn btn-default' %>
    <%= link_to 'List', bulletins_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/bulletins/edit.html.erb
<h1>Editing Bulletin</h1>

<%= render 'form', bulletin: @bulletin %>

<%= link_to 'Show', @bulletin %> |
<%= link_to 'Back', bulletins_path %>

app/views/bulletins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bulletins</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Data Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @bulletins.each do |bulletin| %>
      <tr>
        <td><%= bulletin.title %></td>
        <td><%= bulletin.description %></td>
        <td>
          <%= link_to 'Show', bulletin, class: 'btn btn-default' %>
          <%= link_to 'Edit', edit_bulletin_path(bulletin), class: 'btn btn-default' %>
          <%= link_to 'Destroy', bulletin, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bulletin', new_bulletin_path, class: 'btn btn-default' %>

app/views/bulletins/new.html.erb
<h1>New Bulletin</h1>

<%= render 'form', bulletin: @bulletin %>

app/views/bulletins/show.html.erb
<h2>Preview Bulletin</h2>
<table class="table table-condensed">
  <tr>
    <th>Title</th>
    <td><%= @bulletin.title %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= @bulletin.description %></td>
  </tr>
  <tr>
    <th>Post type</th>
    <td><%= @bulletin.post_type.capitalize %></td>
  </tr>
  <tr>
    <th>Created at</th>
    <td><%= @bulletin.created_at %></td>
  </tr>
</table>

<%= link_to 'Edit', edit_bulletin_path(@bulletin), class: 'btn btn-default' %> |
<%= link_to 'Back', bulletins_path, class: 'btn btn-default' %>