config/routes.rb
# == Route Map
#
#             Prefix Verb   URI Pattern                                      Controller#Action
#               root GET    /                                                welcome#index
#      post_comments POST   /posts/:post_id/comments(.:format)               comments#create
#       post_comment DELETE /posts/:post_id/comments/:id(.:format)           comments#destroy
#              posts GET    /posts(.:format)                                 posts#index
#                    POST   /posts(.:format)                                 posts#create
#           new_post GET    /posts/new(.:format)                             posts#new
#          edit_post GET    /posts/:id/edit(.:format)                        posts#edit
#               post GET    /posts/:id(.:format)                             posts#show
#                    PATCH  /posts/:id(.:format)                             posts#update
#                    PUT    /posts/:id(.:format)                             posts#update
#                    DELETE /posts/:id(.:format)                             posts#destroy
#                    GET    /posts(.:format)                                 posts#index
#                    POST   /posts(.:format)                                 posts#create
#                    GET    /posts/new(.:format)                             posts#new
#                    GET    /posts/:id/edit(.:format)                        posts#edit
#                    GET    /posts/:id(.:format)                             posts#show
#                    PATCH  /posts/:id(.:format)                             posts#update
#                    PUT    /posts/:id(.:format)                             posts#update
#                    DELETE /posts/:id(.:format)                             posts#destroy
#     bulletin_posts GET    /bulletins/:bulletin_id/posts(.:format)          posts#index
#                    POST   /bulletins/:bulletin_id/posts(.:format)          posts#create
#  new_bulletin_post GET    /bulletins/:bulletin_id/posts/new(.:format)      posts#new
# edit_bulletin_post GET    /bulletins/:bulletin_id/posts/:id/edit(.:format) posts#edit
#      bulletin_post GET    /bulletins/:bulletin_id/posts/:id(.:format)      posts#show
#                    PATCH  /bulletins/:bulletin_id/posts/:id(.:format)      posts#update
#                    PUT    /bulletins/:bulletin_id/posts/:id(.:format)      posts#update
#                    DELETE /bulletins/:bulletin_id/posts/:id(.:format)      posts#destroy
#          bulletins GET    /bulletins(.:format)                             bulletins#index
#                    POST   /bulletins(.:format)                             bulletins#create
#       new_bulletin GET    /bulletins/new(.:format)                         bulletins#new
#      edit_bulletin GET    /bulletins/:id/edit(.:format)                    bulletins#edit
#           bulletin GET    /bulletins/:id(.:format)                         bulletins#show
#                    PATCH  /bulletins/:id(.:format)                         bulletins#update
#                    PUT    /bulletins/:id(.:format)                         bulletins#update
#                    DELETE /bulletins/:id(.:format)                         bulletins#destroy
# 

Rails.application.routes.draw do

  root 'welcome#index'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :posts
  resources :bulletins do
    resources :posts
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  context     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  bulletin_id :integer
#  picture     :string
#

class Post < ApplicationRecord
  acts_as_taggable
  belongs_to :bulletin
  mount_uploader :picture, PictureUploader
  has_many :comments, dependent: :destroy

  def tag_list_fixed
    tag_list.to_s
  end

  def tag_list_fixed=(tag_list_string)
    self.tag_list = tag_list_string
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_bulletin
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if @bulletin.present?
      @posts = @bulletin.posts.all
    else
      if params[:tag]
        @posts = Post.tagged_with(params[:tag])
      else
        @posts = Post.all
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = @bulletin.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @bulletin.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to (@bulletin.present? ? [@post.bulletin, @post] : @post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to (@bulletin.present? ? [@post.bulletin, @post] : @post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to (@bulletin.present? ? bulletin_posts_url : posts_url), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bulletin
    @bulletin = Bulletin.find(params[:bulletin_id]) if params[:bulletin_id].present?
  end

  def set_post
    @post = @bulletin.present? ? @bulletin.posts.find(params[:id]) : Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :context, :picture, :picture_cache, :tag_list_fixed)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def bulletin_name(bulletin_id)
    Bulletin.find(bulletin_id).title
  end
end

app/views/posts/post_types/_blog.html.erb
<p id="notice"><%= notice %></p>

<h2><%= bulletin_name params[:bulletin_id] %><small><%= link_to '설정', edit_bulletin_path(params[:bulletin_id]) %></small></h2>

<% @posts.each do |post| %>
  <div class="post">
    <div class="title"><%= post.title %><small>( <%= post.comments.size %> )</small></div>
    <div class="content"><%= simple_format post.context %></div>
    <div>
      <%= link_to 'Show', (@bulletin.present? ? [post.bulletin, post] : post), class: 'btn btn-default' %>
      <%= link_to 'Edit', (@bulletin.present? ? edit_bulletin_post_path(post.bulletin, post) : edit_post_path(post)), class: 'btn btn-default' %>
      <%= link_to 'Destroy', (@bulletin.present? ? [post.bulletin, post] : post), method: :delete, data: { confirm: 'Are you sure?', class: 'btn btn-default' } %>
    </div>
  </div>
<% end %>

<br>

<%= link_to 'New Post', (@bulletin.present? ? new_bulletin_post_path(@bulletin) : new_post_path), class: 'btn btn-default' %>

app/views/posts/post_types/_bulletin.html.erb
<p id="notice"><%= notice %></p>

<h2><%= bulletin_name params[:bulletin_id] %><small><%= link_to '설정', edit_bulletin_path(params[:bulletin_id]) %></small></h2>

<% @posts.each do |post| %>
  <div class="post">
    <div class="title"><%= post.title %><small>( <%= post.comments.size %> )</small></div>
    <div class="content"><%= simple_format post.context %></div>
    <div>
      <%= link_to 'Show', (@bulletin.present? ? [post.bulletin, post] : post), class: 'btn btn-default' %>
      <%= link_to 'Edit', (@bulletin.present? ? edit_bulletin_post_path(post.bulletin, post) : edit_post_path(post)), class: 'btn btn-default' %>
      <%= link_to 'Destroy', (@bulletin.present? ? [post.bulletin, post] : post), method: :delete, data: { confirm: 'Are you sure?', class: 'btn btn-default' } %>
    </div>
  </div>
<% end %>

<br>

<%= link_to 'New Post', (@bulletin.present? ? new_bulletin_post_path(@bulletin) : new_post_path), class: 'btn btn-default' %>

app/views/posts/post_types/_gallery.html.erb
<h2><%= bulletin_name params[:bulletin_id] %><small><%= link_to '설정', edit_bulletin_path(params[:bulletin_id]) %></small></h2>

<div class="gallery">
  <% @posts.each do |post| %>
    <div class="col-lg-3 col-md-3 col-xs-4 picture">
      <div class="image"><%= link_to(image_tag(post.picture_url(:thumb)), [post.bulletin, post]) if post.picture? %></div>
      <div class="title"><%= post.title %><small>( <%= post.comments.size %> )</small></div>
      <div class="content"><%= post.context %></div>
      <% if post.tag_list.size > 0 %>
        <div class="tag_list"><%= fa_icon('tags') + " " + tag_icons(post.tag_list) %></div>
      <% end %>
      <div class="actions">
        <%= link_to fa_icon('eye'), [post.bulletin, post] %>
        <%= link_to fa_icon('edit'), edit_bulletin_post_path(post.bulletin, post) %>
        <%= link_to fa_icon('trash'), [post.bulletin, post], method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
</div>

<br />

<%= link_to 'New post', new_bulletin_post_path, class: 'btn btn-default' %>